[package]
name = "rathole"
version = "0.3.4"
edition = "2021"
authors = ["Yujia Qiao <code@rapiz.me>"]
description = "A reverse proxy for NAT traversal"
license = "Apache-2.0"
repository = "https://github.com/rapiz1/rathole"
readme = "README.md"
build = "build.rs"

[features]
default = ["server", "client", "tls", "noise", "quic", "hot-reload"]

# Run as a server
server = []
# Run as a client
client = []
# TLS support
tls = ["tokio-native-tls"]
# Noise support
noise = ["snowstorm", "base64"]
#QUIC support
quic = ["quinn", "rustls", "rustls-pemfile", "openssl", "futures-util", "futures"]

# Configuration hot-reload support
hot-reload = ["notify"]

# Feature to enable tokio-console. Disabled by default.
# Don't enable it unless for debugging purposes.
console = ["console-subscriber", "tokio/tracing"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true

[profile.bench]
debug = 1

[profile.minimal]
inherits = "release"
opt-level = "z"
lto = true
codegen-units = 1

[dependencies]
tokio = { version = "1", features = ["full"] }
bytes = { version = "1", features = ["serde"] }
clap = { version = "3.0", features = ["derive"] }
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
sha2 = "0.10"
bincode = "1"
lazy_static = "1.4"
hex = "0.4"
rand = "0.8"
backoff = { version="0.3", features=["tokio"] }
tracing = "0.1"
tracing-subscriber = "0.2"
socket2 = "0.4"
fdlimit = "0.2"
tokio-native-tls = { version = "0.3", optional = true }
async-trait = "0.1"
snowstorm = { version = "0.2", optional = true }
base64 = { version = "0.13", optional = true }
notify = { version = "5.0.0-pre.13", optional = true }
console-subscriber = { version = "0.1", optional = true, features = ["parking_lot"] }
const_format = "0.2"
quinn = { version = "0.8.0", optional = true}
rustls = { version = "0.20", default-features = false, features = ["quic"], optional = true }
rustls-pemfile = { version = "0.2.1", optional = true }
openssl = { version = "0.10.38", optional = true }
futures-util = { version = "0.3.11", optional = true}
futures = { version = "0.3.11", optional = true}
[build-dependencies]
vergen = { version = "6.0", default-features = false, features = ["build", "git", "cargo"] }
anyhow = "1.0"
